/***********************************************************************************************
** Program name: Lab 4
** Author: Jordan Hamilton
** Date: 10/21/2018
** Description: This zoo tycoon game starts the player with a sum of money to purchase animals,
** beginning with 1 or 2 penguins, tigers and turtles. The player's money is subtracted for each
** purchased animal. Then, in a while loop, the animals in the zoo age by one day, are fed and
** reduce the players money by the cost of feeding each animal, then an random event occurs:
** an animal of a random type may die, an animal of a random type may have babies according to
** the number of babies associated with that animal's class, the player is rewarded with an
** added random bonus for the day based on the number of tigers in the zoo, or nothing occurs
** that day. Finally, the player's money is increased by the payoff associated with each animal
** in the zoo according to its type. The player is given the opportunity to purchase an adult
** animal, or skip their turn by not making a purchase. A long as the player's money is greater
** than 0 and the player has selected to continue the game at the end of a turn, the game
** continues. If the player runs out of money or quits the game, the program ends.
***********************************************************************************************/

#include <memory>

#include "Menu.hpp"
#include "Instructor.hpp"
#include "Person.hpp"
#include "Student.hpp"
#include "University.hpp"

/***********************************************************************************************
** Description: This program can be run via the lab4 executable generated by make.
***********************************************************************************************/
int main() {

  unsigned seed = time(0);
  srand(seed);

  Menu mainMenu, peopleMenu;

  mainMenu.addMenuItem("View all buildings");
  mainMenu.addMenuItem("View all students and faculty");
  mainMenu.addMenuItem("Select a person to do work");
  mainMenu.addMenuItem("Quit");

  University OSU("Oregon State University");

  std::shared_ptr<Person> student1(new Student("John Appleseed"));
  std::shared_ptr<Person> instructor1(new Instructor("Professor Professorson"));
  std::shared_ptr<Building> building1(new Building("1201 5th St", "Admin Building", 700));
  OSU.people.push_back(student1);
  OSU.people.push_back(instructor1);
  OSU.buildings.push_back(building1);

  switch(mainMenu.getIntChoiceFromPrompt("Select a menu option:", 1, mainMenu.getMenuChoices(), true)) {

    case 1 : OSU.printBuildingInfo();
             break;
    case 2 : OSU.printPeople();
             break;
    default : {}
  }

  /*
  std::vector<std::unique_ptr<BaseClass> > base;
  base.push_back( std_unique_ptr<BaseClass>(new FirstDerivedClass()) );
  base.push_back( std_unique_ptr<BaseClass>(new SecondDerivedClass()) );
  */


  return 0;

}
